#!/bin/bash
PD=`dirname $0`
PROJECT_NAME=sneeu
DJANGO_DIR=$PD/lib

export PYTHONPATH=$PD/$PROJECT_NAME:$DJANGO_DIR
export DJANGO_SETTINGS_MODULE=settings

python $DJANGO_DIR/django/bin/django-admin.py $@